swiftmailer:
    transport:        gmail
    username:         pompiersstjuliendeconcelles
    password:         rd453v3s
    host:             pompyo.loc
    port:             465
    encryption:       ssl
    auth-mode:        login
    spool: { type: 'memory' }
    stream_options:
        ssl:
            allow_self_signed: true
            verify_peer: false
            verify_peer_name: false
