<?php

namespace App\Admin;

use Sonata\AdminBundle\Admin\AbstractAdmin;
use Sonata\AdminBundle\Datagrid\DatagridMapper;
use Sonata\AdminBundle\Datagrid\ListMapper;
use Sonata\AdminBundle\Form\FormMapper;
use Sonata\AdminBundle\Show\ShowMapper;

class ArticleAdmin extends AbstractAdmin
{
    protected function configureFormFields(FormMapper $form)
    {
        $form
            ->add('titre')
            ->add('description')
            ->add('miniature')
        ;
    }

    protected function configureDatagridFilters(DatagridMapper $filter)
    {
        $filter
            ->add('titre')
            ->add('auteur.prenom', null, array(
                'label' => 'Auteur'
            ))
            ->add('dateModif', null, array(
                'label' => 'Date de modification'
            ))
            ->add('dateCreation', null, array(
                'label' => 'Date de création'
            ));
    }

    protected function configureListFields(ListMapper $list)
    {
        $list
            ->add('titre')
            ->add('auteur.prenom', null, array(
                'label' => 'Auteur'
            ))
            ->add('dateModif', null, array(
                'label' => 'Date de modification'
            ))
            ->add('dateCreation', null, array(
                'label' => 'Date de création'
            ))
            ->add('_action', 'actions', array(
                'actions' => array(
                    'show' => array(),
                    'edit' => array(),
                )
            ));
    }

    public function getExportFields()
    {
        return parent::getExportFields(); // TODO: Change the autogenerated stub
    }

    protected function configureShowFields(ShowMapper $show)
    {
        $show
            ->add('titre')
            ->add('description')
            ->add('miniature')
        ;
    }
}